development:
  adapter: mysql2
  encoding: utf8
  database: rails_exercise_ac9
  host: 127.0.0.1
  username: root
  password: 12345678

test:
  adapter: mysql2
  encoding: utf8
  database: rails_exercise_ac9
  host: 127.0.0.1
  username: root
  password: 12345678

production:
  adapter: mysql2
  encoding: utf8
  database: rails_exercise_ac9
  host: localhost
  username: root
  password: 12345678
